on: [push]
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v2
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.10.1
      - run: sudo apt install libgtk-3-dev libgl-dev
      - run: ls /usr/include/GL/ 
      - run: ./build-compressed-release.sh
      - run: ls -l zig-out/bin
      - name: Archive build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: zig-micro-game
          path: |
            zig-out/bin/zig-micro-game
            zig-out/bin/zig-micro-game-compressed
  lint_format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: goto-bus-stop/setup-zig@v2
        with:
            version: 0.10.1
      - run: zig fmt --check src/*.zig