on: [push]
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v2
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.10.1
      - run: ./build-compressed-release.sh
      - run: ls -l zig-out/bin
      - name: Archive build artifacts uncompressed
        uses: actions/upload-artifact@v2
        with:
          name: zig-micro-game
          path: zig-out/bin/zig-micro-game      
      - name: Archive build artifacts compressed
        uses: actions/upload-artifact@v2
        with:
          name: zig-micro-game
          path: zig-out/bin/zig-micro-game-compressed      
  lint_format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: goto-bus-stop/setup-zig@v2
        with:
            version: 0.10.1
      - run: zig fmt --check src/*.zig